output-format: grouped

strictness: veryhigh
doc-warnings: true
test-warnings: false
max-line-length: 120

ignore-paths:
  - docs/

frosted:
  run: false

pyroma:
  run: true

pylint:
  disable:
    - bad-builtin
    - too-few-public-methods
    - missing-docstring
    - star-args

pep8:
  full: true
  disable:
    - E126
