import re
from typing import Any

class FQDN:
    PREFERRED_NAME_SYNTAX_REGEXSTR: str
    ALLOW_UNDERSCORES_REGEXSTR: str
    def __init__(self, fqdn: str, *nothing: Any, **kwargs: Any) -> None: ...
    def __str__(self) -> str: ...
    @property
    def _regex(self) -> re.Pattern[str]: ...
    @property
    def is_valid(self) -> bool: ...
    @property
    def labels_count(self) -> int: ...
    @property
    def is_valid_absolute(self) -> bool: ...
    @property
    def is_valid_relative(self) -> bool: ...
    @property
    def absolute(self) -> str: ...
    @property
    def relative(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
